#include<iostream>
#include<stdlib.h> //NESSECARRY HEADER FILE FOR USING rand() FUNCTION IN C/C++ ------------>1
#include<time.h>   //NESSECSRRY HEADER FILE TO GET NEW RANDOM VALUE AT EVERY SECOND ------->2
using namespace std;

int main(){
    cout<<"HELLO I AM YASH PANDEY"<<endl;
    cout<<"LET's PLAY A GAME WHERE YOU HAVE TO GUESS A NUMBER GENERATED BY COMPUTER"<<endl;
    int number,guess,s=1;
    srand(time(0)); //WE USE THIS BECAUSE OF 2 WHICH WILL PROVIDE US DIFFERENT RANDOM VALUE AT EVERY NEW SECOND
    number = rand()%100 + 1; //WILL GENERATE RANDOM VALUE BETWEEN 1 TO 100 AND NEW VALUE AT EVERY NEW SECOND
    do{
        cout<<"GUESS A NUMBER BETWEEN 1 TO 100 ::: ";
        cin>>guess;
        if(guess>number){
            cout<<"LOWER NUMBER THAN "<<guess<<" !!!"<<endl;
        }
        else if(guess<number){
            cout<<"HIGHER NUMBER THAN "<<guess<<" !!!"<<endl;
        }
        else{
            cout<<"CONGRATULATIONS YOU GUESSED "<<number<<" WHICH IS THE CORRECT NUMBER"<<endl;
            cout<<"YOU GUESSED NUMBER "<<number<<" IN ::: "<<s<<" ATTEMPTS"<<endl;
        }
        s++;
    }while(guess!=number); //DO WHILE LOOP WILL RUN ATLEAST ONCE WHEREAS "for" & "while" LOOP WILLN'T....
    cout<<endl;
    cout<<"HOPE YOU UNDERSTOOD THE CONCEPT"<<endl;
    cout<<"THANKYOU FOR USING ME"<<endl;
    return 0;
}